version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile_django
    volumes:
      - ./backend:/app
    ports:
      - "9000:9000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile_celery
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  

  socket:
    build: 
      context: ./socket
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
   
   frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_DJANGO_URL=https://0.0.0.0:9000
      - REACT_APP_SOCKET_URL=https://0.0.0.0:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - socket

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

