version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile_django
    volumes:
      - ./backend:/app
    ports:
      - "9000:9000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile_celery
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  

  socket:
    build: 
      context: ./socket
      dockerfile: Dockerfile_socket
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
   

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

